POST http://localhost:4000/api/v1/img
Content-Type: application/json

{
    "backImgName": "./img/stage.jpg",
    "frontImgName": "./img/woman.jpg",
    "targetPath": "./",
    "targetImgName": "result.png"
}

POST http://localhost:4000/api/v1/video
Content-Type: application/json

{
    "videoName": "resource/1.mp4",
    "audioName": "resource/2.mp4",
    "targetPath": "resource/",
    "targetFileName": "result.mp4"
}